# 服务端口号
server:
  port: 9040

spring:
  application:
    name: oauthServer
  # 缓存数据库的配置
  redis:
    host: 127.0.0.1
    port: 6379
  # 数据库配置
  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521:ORCL
    username: CWBYSC
    password: CWBYSC
  ## hikari连接池的配置，需要配合配置类，不然启动报错
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

#eureka客户端的配置
eureka:
  instance:
    appname: oauthServer
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/

###feign 默认关闭熔断，请看HystrixFeignConfiguration
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  typeAliasesPackage: com.multimodule.oauth.domain

#打印dao层的DEBUG级别的sql
logging:
  level:
    com.multimodule.oauth.dao: DEBUG