package com.multimodule.userserver.domain;

import java.math.BigDecimal;

public class SysRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE.ROLEID
     *
     * @mbggenerated
     */
    private String roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE.ROLENAME
     *
     * @mbggenerated
     */
    private String rolename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE.AVAILABLEDATE
     *
     * @mbggenerated
     */
    private String availabledate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE.DISABLEDATE
     *
     * @mbggenerated
     */
    private String disabledate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE.SORT
     *
     * @mbggenerated
     */
    private BigDecimal sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE.SENABLE
     *
     * @mbggenerated
     */
    private String senable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE.PID
     *
     * @mbggenerated
     */
    private String pid;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ROLE
     *
     * @mbggenerated
     */
    public SysRole(String roleid, String id, String rolename, String availabledate, String disabledate, BigDecimal sort, String senable, String pid) {
        this.roleid = roleid;
        this.id = id;
        this.rolename = rolename;
        this.availabledate = availabledate;
        this.disabledate = disabledate;
        this.sort = sort;
        this.senable = senable;
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ROLE
     *
     * @mbggenerated
     */
    public SysRole() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE.ROLEID
     *
     * @return the value of SYS_ROLE.ROLEID
     *
     * @mbggenerated
     */
    public String getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE.ROLEID
     *
     * @param roleid the value for SYS_ROLE.ROLEID
     *
     * @mbggenerated
     */
    public void setRoleid(String roleid) {
        this.roleid = roleid == null ? null : roleid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE.ID
     *
     * @return the value of SYS_ROLE.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE.ID
     *
     * @param id the value for SYS_ROLE.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE.ROLENAME
     *
     * @return the value of SYS_ROLE.ROLENAME
     *
     * @mbggenerated
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE.ROLENAME
     *
     * @param rolename the value for SYS_ROLE.ROLENAME
     *
     * @mbggenerated
     */
    public void setRolename(String rolename) {
        this.rolename = rolename == null ? null : rolename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE.AVAILABLEDATE
     *
     * @return the value of SYS_ROLE.AVAILABLEDATE
     *
     * @mbggenerated
     */
    public String getAvailabledate() {
        return availabledate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE.AVAILABLEDATE
     *
     * @param availabledate the value for SYS_ROLE.AVAILABLEDATE
     *
     * @mbggenerated
     */
    public void setAvailabledate(String availabledate) {
        this.availabledate = availabledate == null ? null : availabledate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE.DISABLEDATE
     *
     * @return the value of SYS_ROLE.DISABLEDATE
     *
     * @mbggenerated
     */
    public String getDisabledate() {
        return disabledate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE.DISABLEDATE
     *
     * @param disabledate the value for SYS_ROLE.DISABLEDATE
     *
     * @mbggenerated
     */
    public void setDisabledate(String disabledate) {
        this.disabledate = disabledate == null ? null : disabledate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE.SORT
     *
     * @return the value of SYS_ROLE.SORT
     *
     * @mbggenerated
     */
    public BigDecimal getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE.SORT
     *
     * @param sort the value for SYS_ROLE.SORT
     *
     * @mbggenerated
     */
    public void setSort(BigDecimal sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE.SENABLE
     *
     * @return the value of SYS_ROLE.SENABLE
     *
     * @mbggenerated
     */
    public String getSenable() {
        return senable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE.SENABLE
     *
     * @param senable the value for SYS_ROLE.SENABLE
     *
     * @mbggenerated
     */
    public void setSenable(String senable) {
        this.senable = senable == null ? null : senable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE.PID
     *
     * @return the value of SYS_ROLE.PID
     *
     * @mbggenerated
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE.PID
     *
     * @param pid the value for SYS_ROLE.PID
     *
     * @mbggenerated
     */
    public void setPid(String pid) {
        this.pid = pid == null ? null : pid.trim();
    }
}