package com.multimodule.userserver.domain;

public class SysRoleauth {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLEAUTH.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLEAUTH.PID
     *
     * @mbggenerated
     */
    private String pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLEAUTH.ROLEID
     *
     * @mbggenerated
     */
    private String roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLEAUTH.AUTHNAME
     *
     * @mbggenerated
     */
    private String authname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLEAUTH.AUTHTYPE
     *
     * @mbggenerated
     */
    private String authtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLEAUTH.SOURCEID
     *
     * @mbggenerated
     */
    private String sourceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLEAUTH.SOURCEAID
     *
     * @mbggenerated
     */
    private String sourceaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLEAUTH.CONTENT
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLEAUTH.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ROLEAUTH
     *
     * @mbggenerated
     */
    public SysRoleauth(String id, String pid, String roleid, String authname, String authtype, String sourceid, String sourceaid, String content, String remark) {
        this.id = id;
        this.pid = pid;
        this.roleid = roleid;
        this.authname = authname;
        this.authtype = authtype;
        this.sourceid = sourceid;
        this.sourceaid = sourceaid;
        this.content = content;
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ROLEAUTH
     *
     * @mbggenerated
     */
    public SysRoleauth() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLEAUTH.ID
     *
     * @return the value of SYS_ROLEAUTH.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLEAUTH.ID
     *
     * @param id the value for SYS_ROLEAUTH.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLEAUTH.PID
     *
     * @return the value of SYS_ROLEAUTH.PID
     *
     * @mbggenerated
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLEAUTH.PID
     *
     * @param pid the value for SYS_ROLEAUTH.PID
     *
     * @mbggenerated
     */
    public void setPid(String pid) {
        this.pid = pid == null ? null : pid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLEAUTH.ROLEID
     *
     * @return the value of SYS_ROLEAUTH.ROLEID
     *
     * @mbggenerated
     */
    public String getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLEAUTH.ROLEID
     *
     * @param roleid the value for SYS_ROLEAUTH.ROLEID
     *
     * @mbggenerated
     */
    public void setRoleid(String roleid) {
        this.roleid = roleid == null ? null : roleid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLEAUTH.AUTHNAME
     *
     * @return the value of SYS_ROLEAUTH.AUTHNAME
     *
     * @mbggenerated
     */
    public String getAuthname() {
        return authname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLEAUTH.AUTHNAME
     *
     * @param authname the value for SYS_ROLEAUTH.AUTHNAME
     *
     * @mbggenerated
     */
    public void setAuthname(String authname) {
        this.authname = authname == null ? null : authname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLEAUTH.AUTHTYPE
     *
     * @return the value of SYS_ROLEAUTH.AUTHTYPE
     *
     * @mbggenerated
     */
    public String getAuthtype() {
        return authtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLEAUTH.AUTHTYPE
     *
     * @param authtype the value for SYS_ROLEAUTH.AUTHTYPE
     *
     * @mbggenerated
     */
    public void setAuthtype(String authtype) {
        this.authtype = authtype == null ? null : authtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLEAUTH.SOURCEID
     *
     * @return the value of SYS_ROLEAUTH.SOURCEID
     *
     * @mbggenerated
     */
    public String getSourceid() {
        return sourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLEAUTH.SOURCEID
     *
     * @param sourceid the value for SYS_ROLEAUTH.SOURCEID
     *
     * @mbggenerated
     */
    public void setSourceid(String sourceid) {
        this.sourceid = sourceid == null ? null : sourceid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLEAUTH.SOURCEAID
     *
     * @return the value of SYS_ROLEAUTH.SOURCEAID
     *
     * @mbggenerated
     */
    public String getSourceaid() {
        return sourceaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLEAUTH.SOURCEAID
     *
     * @param sourceaid the value for SYS_ROLEAUTH.SOURCEAID
     *
     * @mbggenerated
     */
    public void setSourceaid(String sourceaid) {
        this.sourceaid = sourceaid == null ? null : sourceaid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLEAUTH.CONTENT
     *
     * @return the value of SYS_ROLEAUTH.CONTENT
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLEAUTH.CONTENT
     *
     * @param content the value for SYS_ROLEAUTH.CONTENT
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLEAUTH.REMARK
     *
     * @return the value of SYS_ROLEAUTH.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLEAUTH.REMARK
     *
     * @param remark the value for SYS_ROLEAUTH.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}